
# MERN application Helm values

# =========================
# Backend
# =========================

backend:
  replicas: 3

  image:
    repository: mern-backend
    tag: latest
    pullPolicy: Never

  service:
    type: ClusterIP
    port: 5050
    targetPort: 5050

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50


# =========================
# Frontend
# =========================

frontend:
  replicas: 1

  image:
    repository: mern-frontend
    tag: v2
    pullPolicy: Never

  service:
    type: NodePort
    port: 5173
    targetPort: 5173


# =========================
# Ingress
# =========================

ingress:
  enabled: true

  className: nginx

  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"

