
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mern-backend

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: mern-backend

  template:
    metadata:
      labels:
        app: mern-backend

    spec:
      containers:
        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

          startupProbe:
            httpGet:
              path: /record/
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /record/
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /record/
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 10

