apiVersion: batch/v1
kind: Job
metadata:
  name: test-failed-job
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: test
          image: busybox
          command: ["sh", "-c", "echo Task failed && exit 1"]
      restartPolicy: Never